import importlib
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
import locale
import logging
from os import getenv

from agent.mcp_adapter import MCPAdapter

LLM_MODEL = getenv("LLM_MODEL", "llama3.1:8b")
AGENT_MODE = getenv("AGENT_MODE", "hybrid")
LLM_HOST = getenv("LLM_HOST", "http://ollama:11434")


def _getenv_int(name: str, default: int) -> int:
    value = getenv(name)
    if value is None:
        return default
    value = value.strip()
    if not value:
        return default
    try:
        return int(value)
    except ValueError:
        logging.warning(f"Invalid value for {name}: {value!r}. Using default {default}.")
        return default

SYSTEM_PROMPT = getenv(
    "AGENT_SYSTEM_PROMPT",
    "You are a stateless AI payment agent. Do not keep memory between requests. "
    "When MCP tools are available, discover tools and use tool calls for actions instead of hardcoded workflows. "
    "If no tool is available for a requested action, respond clearly and ask for required tool availability."
)

class PaymentAgent:
    def __init__(self, mode=None):
        os_lang, _ = locale.getdefaultlocale()
        self.default_language = (os_lang[:2] if os_lang else "en").lower()
        self.model = LLM_MODEL
        self.mode = mode if mode else AGENT_MODE  
        self.llm = None
        self.mcp_adapter = MCPAdapter()
        self._init_llm()

    def _init_llm(self):
        if self.llm is not None:
            return

        try:
            import requests
            try:
                response = requests.post(
                    f"{LLM_HOST}/api/show",
                    json={"name": LLM_MODEL},
                    timeout=5
                )
                if response.status_code == 404:
                    logging.info(f"Model {LLM_MODEL} not found. Pulling from Ollama library...")
                    pull_response = requests.post(
                        f"{LLM_HOST}/api/pull",
                        json={"name": LLM_MODEL},
                        stream=True,
                        timeout=600
                    )
                    for line in pull_response.iter_lines():
                        if line:
                            logging.info(line.decode('utf-8'))
                    logging.info(f"✅ Model {LLM_MODEL} downloaded successfully!")
            except requests.exceptions.RequestException as e:
                logging.warning(f"Could not check/pull Ollama model: {e}")
            
            ChatOllama = importlib.import_module("langchain_ollama").ChatOllama
            self.llm = ChatOllama(
                model=LLM_MODEL, 
                base_url=LLM_HOST,
                num_ctx=_getenv_int("LLM_CONTEXT_LENGTH", 2048),
                num_parallel=_getenv_int("LLM_NUM_PARALLEL", 4),
                keep_alive=getenv("LLM_KEEP_ALIVE", "30m"),
            )
        except Exception as e:
            logging.error(f"Ollama LLM initialization failed: {e}")
            self.llm = None
            raise

    async def process(self, message: str, state: dict = None, return_state: bool = False):
        if not message or not message.strip():
            response_text = "Message cannot be empty."
        else:
            response_text = self.mcp_adapter.process(
                message.strip(),
                invoke_llm=self._invoke_llm,
                system_prompt=SYSTEM_PROMPT,
            )
            if not response_text:
                response_text = "No response generated by model."

        final_state = {
            "messages": [HumanMessage(content=message), AIMessage(content=response_text)],
            "response": response_text,
            "mode": self.mode,
            "detected_language": self.default_language,
            "awaiting_next": None,
            "result": {}
        }

        if return_state:
            return final_state

        return response_text

    def _invoke_llm(self, messages):
        llm_response = self.llm.invoke(messages)
        return str(getattr(llm_response, "content", "")).strip()
